# Generated by Django 2.2 on 2021-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosite', '0002_stud_data_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_data',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
