# Generated by Django 2.2 on 2021-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosite', '0003_auto_20210413_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_data',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
    ]
