# Generated by Django 2.2 on 2021-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosite', '0004_auto_20210413_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_data',
            name='dob',
            field=models.DateField(),
        ),
    ]
